
- fullName: "Wolf"
  simpleName: "W"
  weight: 15                     # start weight
  moveSpeed: 5
  defaultCount: 1                 # count to produce
  chancesPercent:
    "chanceToEat": 30             #percents
    "criticalWeight": 10          #minimal Weight to priority eat
    "Rabbit": 60                  #chance to attack
    "chanceToReproduce": 80
    "fullWeight": 25
    "toEatUp": 6                  # how many need to get full weight


- fullName: "Rabbit"
  simpleName: "R"
  weight: 5
  moveSpeed: 3
  defaultCount: 200
  chancesPercent:
    "criticalWeight": 60
    "move": 50
    "attackRabbit": 60
    "chanceToReproduce": 80
    "fullWeight": 10
